import { readFileSync } from "node:fs";
import { join } from "node:path";
import { prisma } from "../prisma.ts";
import { ALL_MUSCLES } from "../muscles.ts";
import type { Muscle } from "@prisma/client";

/**
 * The shared exercise catalog.
 *
 * Content is generated by `scripts/build-catalog.mjs` from free-exercise-db and
 * checked in as `prisma/catalog/exercises.json`. The script is never run at
 * build or deploy time: the catalog must not change because an upstream
 * repository changed under us, and a deploy must not depend on a third-party
 * URL being reachable.
 *
 * Seeding is idempotent and runs as a script rather than a data migration,
 * because production applies schema with `prisma db push` and never runs
 * `migrate deploy` - a data migration would never reach it. See
 * `npm run db:seed-catalog`.
 */

export interface CatalogEntry {
  slug: string;
  name: string;
  musclesPrimary: Muscle[];
  musclesSecondary: Muscle[];
  description: string;
  equipment: string;
  level: string;
  mechanic: string;
  force: string;
}

const CATALOG_PATH = join(process.cwd(), "prisma", "catalog", "exercises.json");

/**
 * The catalog content, validated.
 *
 * Every muscle is checked against the closed vocabulary here rather than
 * trusting the generator, because this is the last point before the values
 * reach a column the volume chart depends on. A bad tag must fail the seed
 * loudly, not land in the database and be discovered as a wrong number months
 * later.
 */
export function readCatalogFile(path: string = CATALOG_PATH): CatalogEntry[] {
  const entries = JSON.parse(readFileSync(path, "utf8")) as CatalogEntry[];
  const valid = new Set<string>(ALL_MUSCLES);
  const seen = new Set<string>();

  for (const entry of entries) {
    if (!entry.slug || !/^[a-z0-9_]+$/.test(entry.slug)) {
      throw new Error(`Catalog entry has an invalid slug: ${entry.slug}`);
    }
    if (seen.has(entry.slug)) {
      throw new Error(`Catalog has a duplicate slug: ${entry.slug}`);
    }
    seen.add(entry.slug);

    if (entry.musclesPrimary.length === 0) {
      throw new Error(`Catalog entry ${entry.slug} has no primary muscle.`);
    }
    for (const muscle of [...entry.musclesPrimary, ...entry.musclesSecondary]) {
      if (!valid.has(muscle)) {
        throw new Error(
          `Catalog entry ${entry.slug} names an unknown muscle: ${muscle}`,
        );
      }
    }
  }

  return entries;
}

/**
 * Brings the catalog table in line with the checked-in content.
 *
 * Idempotent, so it is safe to run on every deploy and safe to run twice.
 * Entries are upserted rather than replaced wholesale: deleting and reinserting
 * would break any future foreign key pointing at a slug, and would churn rows
 * that did not change.
 */
export async function seedCatalog(
  entries: CatalogEntry[] = readCatalogFile(),
): Promise<{ written: number }> {
  for (const entry of entries) {
    const data = {
      name: entry.name,
      musclesPrimary: entry.musclesPrimary,
      musclesSecondary: entry.musclesSecondary,
      description: entry.description,
      equipment: entry.equipment,
      level: entry.level,
      mechanic: entry.mechanic,
      force: entry.force,
    };
    await prisma.exerciseCatalog.upsert({
      where: { slug: entry.slug },
      // `tips`, `mistakes` and `videoUrl` are deliberately absent from the
      // update: they are empty in the import and exist to be curated by hand.
      // Re-seeding must not wipe curation.
      update: data,
      create: { slug: entry.slug, ...data },
    });
  }
  return { written: entries.length };
}

/** The whole catalog, by slug. */
export async function listCatalog() {
  return prisma.exerciseCatalog.findMany({ orderBy: { name: "asc" } });
}

/** One catalog entry, or null. */
export async function getCatalogEntry(slug: string) {
  return prisma.exerciseCatalog.findUnique({ where: { slug } });
}
